### PR TITLE
Sending logging to stderr

### PR DESCRIPTION
**Pull request by thedumbterminal**
Also added a debug option to the CLI tool.

Addresses issue: https://github.com/thedumbterminal/jsonschema-bigquery/issues/31

### CODE REVIEW

**Comment by thedumbterminal** [comment]
@paparomeo The library itself does not have any logging, only the CLI tool. So I've improved the errors thrown by the library so now they stringify with nice pretty printed JSON.

**Comment by paparomeo** [comment]
`src/gbq.js` has some logging, does it not? Or am I misreading?

**Comment by thedumbterminal** [comment]
@paparomeo `src/gbq.js` does have logging but it is not included from `src/converter.js` which is the only file exported as a library.

**Comment by paparomeo** [comment]
Fair enough @thedumbterminal!

**Pull request merged**
